# Control how the program acts
[behaviour]
# The valid modes are: "file" or "cmdline"
read_mode       = "file"
# Should the program output to a log file
logging_enabled = true

# Modifies the output of the log file
[logging]
level       = "ALL"
destination = "runtime.log"
format      = "%(asctime)s [%(filename)s:%(lineno)04d] %(levelname)-8s - %(message)s"
datefmt     = "%H:%M:%S"

# Define the logging levels used by the logger
[logging.levels]
CRITICAL        = 50
INFO            = 20
DEBUG           = 10
VERBOSE         = 9
HIGHLY_VERBOSE  = 8
EAT_STACK       = 7
ALL             = 5

# Dev options only used to assist with debugging
[dev]
# If no file was specified in the arguments, use this instead
# Overrides default cmdline behaviour
default_filename  = "examples/loops.sap"
# This defines how errors are treated
# If true, it will raise an error with the full stack trace,
# useful for debugging purposes
# If false, it will print the error normally
raise_error_stack = false
